from . import projects
from . import school_department
from . import tvet_courses
from . import school_subjects
from . import school_city
from . import school_semester
from . import academic_year
from . import school_class
from . import school_shift
from . import student_registration
from . import student_admission
from . import nationality
from . import class_location
from . import student_relationship
from . import exam_result_entry
from . import special_needs
from . import idp_name
from . import manage_timetable
from . import create_lecturer
from . import assign_lecturer
from . import exam_type
from . import attendance_sheet
from . import assign_course
from . import approve_course
from . import approve_lecturer
