# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from . import academic_month
from . import academic_year
from . import account_move
from . import approve_course
from . import approve_lecturer
from . import assign_course
from . import assign_lecturer
from . import attendance_sheet
from . import class_location
from . import class_room
from . import course_subject
from . import create_lecturer
from . import exam_result
from . import exam_result_entry
from . import exam_type
from . import grading
from . import hr_employee
from . import manage_timetable
from . import nationality
from . import res_city
from . import res_company
from . import res_config_settings
from . import res_partner
from . import res_user
from . import school_department
from . import school_shift
from . import semester
from . import student_admission
from . import student_registration
from . import awarding_system
from . import un_install_rescrite_module
from . import school_subject
from . import projects
from . import special_needs
from . import idp_name
from . import state