from . import projects
from . import school_department
from . import tvet_courses
from . import school_subjects
from . import school_city
from . import school_semester
from . import academic_year
from . import school_class
from . import school_shift
from . import student_registration
from . import student_admission